version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: idor_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: idor_lab
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  vulnerable_app:
    build: ./app/vulnerable_app
    container_name: idor_vulnerable_app
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: idor_lab
    ports:
      - "5000:5000"
    depends_on:
      - db

  secure_app:
    build: ./app/secure_app
    container_name: idor_secure_app
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: idor_lab
    ports:
      - "5001:5000"
    depends_on:
      - db
